extends Node2D

enum {HIGH, LOW, MIDDLE, ROCK, TREE, WATER}

const TILE_DIAMETER = 55
const TILE_ROW_HEIGHT = 40

const START_POSITION = Vector2(330, 110)

const LEVEL_1 = [
	[null, 	null, 	HIGH, 	MIDDLE, 	LOW, 	LOW, 	null, 	null, 	null],
	[null, 	ROCK, 	HIGH, 	LOW, 	LOW, 	LOW, 	LOW, 	null, 	null],
	[HIGH, 	HIGH, 	ROCK, 	LOW, 	WATER, 	TREE, 	LOW, 	LOW, 	null],
	[MIDDLE,	LOW, 	LOW, 	LOW, 	LOW, 	WATER, 	TREE, 	LOW, 	LOW],
	[LOW, 	LOW, 	WATER, 	LOW, 	TREE, 	LOW, 	WATER, 	LOW, 	LOW],
	[LOW, 	LOW, 	TREE, 	WATER, 	LOW, 	LOW, 	LOW, 	LOW, 	MIDDLE],
	[null, 	LOW, 	LOW, 	TREE, 	WATER, 	LOW, 	ROCK, 	HIGH, 	HIGH],
	[null, 	null, 	LOW, 	LOW, 	LOW, 	LOW, 	HIGH, 	ROCK, 	null],
	[null, 	null, 	null, 	LOW, 	LOW, 	MIDDLE, 	HIGH, 	null, 	null]
]

const LEVEL_2 = [
	[LOW]
]

enum TOKEN_TYPE {
	NUMBER, STRING, BOOLEAN, IDENTIFIER, KEYWORD,
	OPEN_PARENTHESIS, CLOSE_PARENTHESIS, OPEN_BRACE, CLOSE_BRACE, COMMA,
	ADD, MULTIPLY, EQUALS,
	SEMICOLON,
	EOF
}

const TOKEN_TYPE_TO_STRING = {
	TOKEN_TYPE.NUMBER: 'NUMBER',
	TOKEN_TYPE.STRING: 'STRING',
	TOKEN_TYPE.BOOLEAN: 'BOOLEAN',
	TOKEN_TYPE.IDENTIFIER: 'IDENTIFIER',
	TOKEN_TYPE.KEYWORD: 'KEYWORD',
	TOKEN_TYPE.OPEN_PARENTHESIS: 'OPEN_PARENTHESIS',
	TOKEN_TYPE.CLOSE_PARENTHESIS: 'CLOSE_PARENTHESIS',
	TOKEN_TYPE.OPEN_BRACE: 'OPEN_BRACE',
	TOKEN_TYPE.CLOSE_BRACE: 'CLOSE_BRACE',
	TOKEN_TYPE.COMMA: 'COMMA',
	TOKEN_TYPE.ADD: 'ADD',
	TOKEN_TYPE.MULTIPLY: 'MULTIPLY',
	TOKEN_TYPE.EQUALS: 'EQUALS',
	TOKEN_TYPE.SEMICOLON: 'SEMICOLON',
	TOKEN_TYPE.EOF: 'EOF',
}

enum ASL_NODE_TYPE {
	NUMBER, STRING, VARIABLE,
	ASSIGNMENT, OPERATION, DECLARATION
}

const ASL_NODE_TYPE_TO_STRING = {
	ASL_NODE_TYPE.NUMBER: 'NUMBER',
	ASL_NODE_TYPE.STRING: 'STRING',
	ASL_NODE_TYPE.VARIABLE: 'VARIABLE',
	ASL_NODE_TYPE.ASSIGNMENT: 'ASSIGNMENT',
	ASL_NODE_TYPE.OPERATION: 'OPERATION',
	ASL_NODE_TYPE.DECLARATION: 'DECLARATION',
}
